# 项目相关配置
fuce:
  #名称
  name: ithink
  #版本
  version: 4.1
  #版权年份
  copyright-year: 2018
  #文件上传路径
  #defaultBaseDir: D:/v2file/
  defaultBaseDir: /home/ecm/image/
  #地址是否放入项目static目录，如果未Y 放入项目得static。 profile配置失效。  为N存放在D:/v2file/ 前端读取相同，不受影响
  isstatic: N
  #开启存放静态文件夹后目录
  isroot_dir: static/file_upload/
  #存放图片地址
  #picDir: D:/v2file/pic/
  picDir: /home/ecm/image/
  avatDir: /home/ecm/avat/
  #contract_dir: D:/pdffile/contract/
  contract_dir: /home/ecm/contractfile/
  #邮件功能
  #邮箱发送smtp
  email-smtp: smtp.exmail.qq.com
  #邮箱发送端口
  email-port: 465
  #发送邮箱登录账号
  email-account: ithink@sina.com
  #发送邮箱登录密码
  email-password: emailpassword
  #实例演示开关 启动该模式删除增加修改会弹出演示模式提示框
  demo-enabled: false
  #漂亮得拖动验证码 默认false普通验证码、true滚动验证码
  roll-verification: false
  #公司公章名称
  default_company: 武汉闻嘉瑜信息技术有限公司
  #公章用途
  default_purpose: 合同专用章
  #重要文件保存
  fileDir: /home/ecm/contractfile/
#腾讯云配置
tencent:
  appId: 135243643
  # 腾讯云的SecretId（永久的，可在控制台开启或关闭）
  secretId: AFCVFDSISDAJCADSFDERGVFDBRGREDBVD
  # 腾讯云的SecretKey（永久的，可在控制台开启或关闭）
  secretKey: ASCDFSVRQDCSAVFRSBVSRFESBSGFSEF
  # 腾讯云的allowPrefix(允许上传的路径)
  allowPrefix: '*'
  # 腾讯云的访问基础链接:
  baseUrl: https://ithink-12432131324.cos.ap-shanghai.myqcloud.com
  # 腾讯云的cdn访问链接:
  cdnUrl: https://democc.com
  # 腾讯云的bucket (存储桶)
  bucket: ithink-12432131324
  # 腾讯云的临时密钥时长(单位秒)
  durationSeconds: 1800
  # 腾讯云的region(bucket所在地区)
  region: ap-shanghai
#tomcat config
server :
  port : 8080
  ##项目名字配置
  #servlet :
  #  context-path : /demo
  tomcat :
    uri-encoding : UTF-8
    #shiro 报错修改的地方
    max-connections: 200000
    max-http-form-post-size: 9000000
    threads:
      max: 128
      min-spare: 5
    remote:
      port-header: X-Forwarded-Port
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
  forward-headers-strategy: native

spring :
  # 环境 dev|test|prod
  profiles :
    active : dev
    #引入其他配置文件，例如ftpHX 未配置文件application-ftpHX.yml
    #include: ftpHX,ftpCloud
  servlet:
    multipart:
      #设置总上传的数据大小
      max-request-size: 100MB
      #单个文件大小
      maxFileSize : 30MB
        #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
  #热部署模块
  devtools:
    restart:
      #热部署开关
      enabled: true
      #指定热部署的目录
      additional-paths: src/main/java
      #指定目录不更新
      exclude: test/**
  mvc:   #静态文件
    static-path-pattern : /static/**
  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    ssl: false
    database: 0
    host: 49.235.108.44
    port: 6379
    password: 1qaz2wsx
    timeout: 1000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

#mybatis:
#  #配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations : classpath*:mybatis/*/*.xml
#  #mybatis提供三种sql执行器，分别是SIMPLE、REUSE、BATCH。
#  executor-type : reuse
#  #搜索指定包别名
#  typeAliasesPackage : com.*.model
#  #该配置项就是指将带有下划线的表字段映射为驼峰格式的实体类属性。
#  configuration :
#    map-underscore-to-camel-case : true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
oss:
  enable: true
  info: true
  path-style-access: false  #使用云OSS 需要关闭
  endpoint: http://127.0.0.1:9000 #对应上图 ③ 处配置
  access-key: minioadmin  # 上文创建的AK
  secret-key: minioadmin # 上文创建的SK
  bucket-name: v2-cloud  # 上文创建的桶名称

pageoffice:
  #posypath: d:/lic/
  posypath: static/lic/
  popassword: 111111